In [12]:
import pandas as pd
import numpy as np
df=pd.read_csv("census_village_data_at_district_level_Explorin.csv")
df.head(10)

,state_code,state_name,district_code,district_name,total_households,total_population,total_population_male,total_population_female,total_population_SC,total_population_male_SC,...,govt_polytechnic_college,pvt_polytechnic_college,govt_vocational_ITI_training,pvt_vocational_ITI_training,govt_non_formal_training_centre,pvt_non_formal_training_centre,govt_disabled_school,pvt_disabled_school,govt_other_education,pvt_other_education
0,1.0,JAMMU & KASHMIR,1.0,Kupwara,101930.0,765625.0,412038.0,353587.0,872.0,870.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,JAMMU & KASHMIR,2.0,Badgam,89417.0,655833.0,343385.0,312448.0,86.0,78.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,JAMMU & KASHMIR,3.0,Leh(Ladakh),14905.0,87816.0,48411.0,39405.0,108.0,89.0,...,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,222.0
3,1.0,JAMMU & KASHMIR,4.0,Kargil,16147.0,124464.0,67703.0,56761.0,10.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128.0,246.0
4,1.0,JAMMU & KASHMIR,5.0,Punch,83045.0,438205.0,229774.0,208431.0,278.0,248.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,JAMMU & KASHMIR,6.0,Rajouri,122645.0,590101.0,310748.0,279353.0,46141.0,23907.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1.0,JAMMU & KASHMIR,7.0,Kathua,101651.0,526722.0,278126.0,248596.0,119693.0,63321.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1.0,JAMMU & KASHMIR,8.0,Baramula,125346.0,825539.0,432399.0,393140.0,323.0,304.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1.0,JAMMU & KASHMIR,9.0,Bandipore,48794.0,326871.0,172263.0,154608.0,105.0,105.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1.0,JAMMU & KASHMIR,10.0,Srinagar,2844.0,17313.0,8916.0,8397.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0